# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_linux_amd64'

  - id: linux-arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}_linux_arm64'

  - id: windows-amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - windows
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_windows_amd64.exe'

  - id: darwin-amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - darwin
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_darwin_amd64'

archives:
  - id: linux-amd64
    builds:
      - linux-amd64
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_amd64'

  - id: linux-arm64
    builds:
      - linux-arm64
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_arm64'

  - id: windows-amd64
    builds:
      - windows-amd64
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_windows_amd64'

  - id: darwin-amd64
    builds:
      - darwin-amd64
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_darwin_amd64'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: chijiajian
    name: zstack-cli-go

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
      - '^style:'
