version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_linux_amd64'

  - id: windows-amd64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - windows
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_windows_amd64'

archives:
  - id: linux-amd64
    format: tar.gz
    files:
      - none*
    builds:
      - id: linux-amd64

  - id: windows-amd64
    format: zip
    files:
      - none*
    builds:
      - id: windows-amd64

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: zstackio
    name: zstack-cli
  draft: true
  replace_existing_draft: true

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
      - '^style:'
